### ISSUE TITLE
EKGH & EKCC

### ISSUE THREAD

**Issue by johanohly** [lxndrblz/Airports#180]
Those ones I noticed, there are probably a lot more small airports in denmark missing.

**Comment by lxndrblz** [comment]
Hi there,

I am only tracking IATA airports, that's why these are not on the list. These do not have an IATA code associated with them.

**Comment by johanohly** [comment]
Ah that is fair, I am not sure how I missed that. I probably got ICAO and IATA mixed up :)

Do you have a recommendation for a complete airport dataset? 
I have looked at [this one](https://www.flightradar24.com/_json/airports.php), which seems to be missing a lot of airports as well. 
I have also looked at the [OpenFlights dataset](https://github.com/jpatokal/openflights/tree/master/data) which is looking very complete.

**Comment by lxndrblz** [comment]
For ICAO Codes, I'd recommend this one:

https://raw.githubusercontent.com/komed3/airportmap-database/master/airport.csv

Openflights tends to be a bit outdated and messy, that's why I have started tracking airports myself.

**Comment by johanohly** [comment]
> For ICAO Codes, I'd recommend this one:
> 
> [komed3/airportmap-database@`master`/airport.csv (raw)](https://raw.githubusercontent.com/komed3/airportmap-database/master/airport.csv)
> 
> Openflights tends to be a bit outdated and messy, that's why I have started tracking airports myself.

That looks promising, thank you very much!
