### ISSUE TITLE
The difference between airports.csv and citycodes.csv

### ISSUE THREAD

**Issue by lensory** [lxndrblz/Airports#44]
Dear Alexander,

Thanks for your sharing data. It seems that these two files has the same fields and formats. Could you please give more information on the difference of these two files?

**Comment by lxndrblz** [comment]
Hi there,

the explaination is fairly simple. The airports.csv contains "real world" airports with a runway and terminals etc. In contrast, the citycodes file contains a list of codes, which are designated to metropolitan areas that have multiple Airports. For example PAR is the area code for Paris, as there are two airports in the immediate Paris region (CDG + ORY) it basically links to both of them.
