### ISSUE TITLE
Cities are not completely available in Airport.csv file

### ISSUE THREAD

**Issue by Raakh** [lxndrblz/Airports#64]
Hello,

I just checked and found airports are available whilst city section of this file is not available. Do you have complete list of cities?

Best Regards

**Comment by lxndrblz** [comment]
Hi @Raakh

City codes can be found in the following file:
https://github.com/lxndrblz/Airports/blob/main/citycodes.csv

The cities for the airports are reverse geocoded. If no city could be determined, then they might be empty.
