### ISSUE TITLE
incorrect IATA for Mpanda Airport

### ISSUE THREAD

**Issue by sub4biz** [lxndrblz/Airports#65]
Mpanda Airport (IATA: NPY, ICAO: HTMP) is an airport in western Tanzania serving the town of Mpanda and the surrounding Katavi Region.
MOW is city IATA for Moscow, RU

**Comment by lxndrblz** [comment]
Hi @sub4biz ,

The IATA code of NPY is actually in the list:

https://github.com/lxndrblz/Airports/blob/16fc6ed7da62528495e680ac12e8643cfafac530/airports.csv#L2558

I am going to fix the city code for Moscow. Thanks for pointing this out!
